"""NLP Chatbot package."""

from .config import (
    DEFAULT_VECTOR_DB_PATH,
    DEFAULT_EMBEDDING_MODEL_PATH,
    DEFAULT_CHUNK_SIZE,
    DEFAULT_CHUNK_OVERLAP,
    DEFAULT_MIN_CHUNK_SIZE,
    DEFAULT_MAX_TITLE_LENGTH,
    DEFAULT_MODEL_NAME,
    INPUT_DOCUMENTS_DIR,
    PROCESSED_DOCUMENTS_DIR
)

__all__ = [
    'DEFAULT_VECTOR_DB_PATH',
    'DEFAULT_EMBEDDING_MODEL_PATH',
    'DEFAULT_CHUNK_SIZE',
    'DEFAULT_CHUNK_OVERLAP',
    'DEFAULT_MIN_CHUNK_SIZE',
    'DEFAULT_MAX_TITLE_LENGTH',
    'DEFAULT_MODEL_NAME',
    'INPUT_DOCUMENTS_DIR',
    'PROCESSED_DOCUMENTS_DIR'
] 